# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peep < Formula
  desc "A terminal UI for exploring JSON"
  homepage "https://github.com/guisolski/peep"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guisolski/peep/releases/download/v0.3.0/peep_0.3.0_darwin_amd64.tar.gz"
      sha256 "c45cfca2892a186a4166eab6c10284b4f4863da61e3e5ec721094b17f6304a83"

      define_method(:install) do
        bin.install "peep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guisolski/peep/releases/download/v0.3.0/peep_0.3.0_darwin_arm64.tar.gz"
      sha256 "68c150745bdb2c48747ce3877351707050ba334284759992d15caa95a68c03e5"

      define_method(:install) do
        bin.install "peep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guisolski/peep/releases/download/v0.3.0/peep_0.3.0_linux_amd64.tar.gz"
      sha256 "53bb1b8771e6eb85b8ab472221935a4ce485d4145b720ef019fbd0a22d4e3fa8"
      define_method(:install) do
        bin.install "peep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guisolski/peep/releases/download/v0.3.0/peep_0.3.0_linux_arm64.tar.gz"
      sha256 "49bd7fb572a8c606959ff5f9e7242b7d9cf9e285a8e4a7a141f9c5adbd8be73d"
      define_method(:install) do
        bin.install "peep"
      end
    end
  end

  test do
    system "#{bin}/peep --version"
  end
end
