# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peep < Formula
  desc "A terminal UI for exploring JSON"
  homepage "https://github.com/guisolski/peep"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guisolski/peep/releases/download/v0.2.0/peep_0.2.0_darwin_amd64.tar.gz"
      sha256 "1e0a437be75bcda2a431a5ce947f1e4f6dabf06324b35274e9c2bed18a0e502f"

      define_method(:install) do
        bin.install "peep"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guisolski/peep/releases/download/v0.2.0/peep_0.2.0_darwin_arm64.tar.gz"
      sha256 "c6266c9ca34b36a516f976804014c457ffd88ef7f9a9a5dbbbac2bd5afb6a221"

      define_method(:install) do
        bin.install "peep"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guisolski/peep/releases/download/v0.2.0/peep_0.2.0_linux_amd64.tar.gz"
      sha256 "647f456e172041ed2cb321d93267cfd10cbdfe01c99cf45d3359aadc590e65a0"
      define_method(:install) do
        bin.install "peep"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guisolski/peep/releases/download/v0.2.0/peep_0.2.0_linux_arm64.tar.gz"
      sha256 "b9216c617c15ab608184cd309f1f8ad15fea482454ea55574469e9275d3e9854"
      define_method(:install) do
        bin.install "peep"
      end
    end
  end

  test do
    system "#{bin}/peep --version"
  end
end
